default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: Recipe_app_development
  username: tjay
  password: nemuqa89

test:
  <<: *default
  database: Recipe_app_test
  username: tjay
  password: nemuqa89

production:
  <<: *default
  database: Recipe_app_test
  username: <%= ENV["POSTGRES_USERNAME"] %>
  password: <%= ENV["POSTGRES_PASSWORD"] %>